services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - back-tier

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${DOCKERMINIOROOTUSER}
      - MINIO_ROOT_PASSWORD=${DOCKERMINIOROOTPASS}
    volumes:
      - ./minio/data:/data
    networks:
      - back-tier
    command: server --console-address ":9001" /data

  app:
    image: signage-api
    build: .
    ports:
      - "8088:8088"
    environment:
      - GIN_MODE=release
    networks:
      - back-tier

  mongo:
    image: mongo
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DOCKERMONGOROOTUSER}
      MONGO_INITDB_ROOT_PASSWORD: ${DOCKERMONGOROOTPWD}
    volumes:
      - ./db/data:/data/db 
    networks:
      - back-tier


networks:
  back-tier: {}